// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAiZfoZIt9MojK5h0VngF5-4st_QX6uyw',
    appId: '1:777533853363:web:a61dea52a3cae4700aaac6',
    messagingSenderId: '777533853363',
    projectId: 'eventati-book',
    authDomain: 'eventati-book.firebaseapp.com',
    storageBucket: 'eventati-book.firebasestorage.app',
    measurementId: 'G-MZ13X6WPP5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXrIaKZIHOjfjU9C4YRuxNFt5NgR7oEQI',
    appId: '1:777533853363:android:5efbb706e15408170aaac6',
    messagingSenderId: '777533853363',
    projectId: 'eventati-book',
    storageBucket: 'eventati-book.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJCsbi0aG7WnAZcoXzTKxldX-WWKUv7EU',
    appId: '1:777533853363:ios:ef0aea5743a119ff0aaac6',
    messagingSenderId: '777533853363',
    projectId: 'eventati-book',
    storageBucket: 'eventati-book.firebasestorage.app',
    iosBundleId: 'com.example.eventatiBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJCsbi0aG7WnAZcoXzTKxldX-WWKUv7EU',
    appId: '1:777533853363:ios:ef0aea5743a119ff0aaac6',
    messagingSenderId: '777533853363',
    projectId: 'eventati-book',
    storageBucket: 'eventati-book.firebasestorage.app',
    iosBundleId: 'com.example.eventatiBook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAiZfoZIt9MojK5h0VngF5-4st_QX6uyw',
    appId: '1:777533853363:web:cc241487c968ac610aaac6',
    messagingSenderId: '777533853363',
    projectId: 'eventati-book',
    authDomain: 'eventati-book.firebaseapp.com',
    storageBucket: 'eventati-book.firebasestorage.app',
    measurementId: 'G-6LNR55XXH9',
  );
}
